Repository loco-local-collection/frontend, pull requests merged in 2025-03, with the labels that each got.

#3 기본 문서 작성
  .env.example
  .github/pull_request_template.md
  .gitignore
  README.md
Labels: docs

#7 드롭다운 공통 컴포넌트
  src/components/atoms/Dropdown.tsx
  src/components/atoms/DropdownItem.tsx
Labels: feature

#9 메뉴 컴포넌트
  src/components/atoms/Menu.tsx
  src/components/atoms/MenuItem.tsx
Labels: refactor

#21 Test/#20/testing library setup
  .gitignore
  __tests__/mock-api/mock-browser.ts
  jest.config.ts
  package-lock.json
  package.json
  playwright.config.ts
  public/mockServiceWorker.js
  src/app/test/page.tsx
  src/components/msw-wrapper/MswWrapper.tsx
  src/components/msw-wrapper/TestButton.tsx
  src/components/msw-wrapper/mockBrowser.ts
  vitest.config.ts
Labels: test

#27 Map 페이지 UI 세부 구현
  src/app/(spot)/edit/[id]/page.tsx
  src/app/(spot)/map/[id]/page.tsx
  src/components/atoms/Avatar.tsx
  src/components/atoms/ImageCarousel.tsx
  src/components/molecules/Card.tsx
  src/components/molecules/PlaceCard.tsx
  src/components/spotMap/ClusterMarker.tsx
  src/components/spotMap/CommentSection.tsx
  src/components/spotMap/ImageGallerySection.tsx
  src/components/spotMap/MapContainer.tsx
  src/components/spotMap/MapSidebar.tsx
  src/components/spotMap/MapSidebarHeader.tsx
  src/components/spotMap/MarkerWindow.tsx
  src/components/spotMap/Markers.tsx
  src/components/spotMap/PlaceDetailModal.tsx
  src/components/spotMap/TitleMarker.tsx
  src/types/spot.ts
Labels: feature
